env:
  browser: true
  es2021: true
extends:
  - next/core-web-vitals
  - airbnb
  - prettier
  - plugin:prettier/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
rules:
  react/jsx-props-no-spreading:
    - 0
  react/prop-types:
    - 0
  react/jsx-filename-extension:
    - 1
    - extensions:
        - .js
        - .jsx
  import/extensions:
  - error
  - ignorePackages
  - js: never
    jsx: never
    ts: never
    tsx: never

settings:
  import/resolver:
    node:
      extensions:
        - .js"
        - .jsx
        - .ts
        - .tsx
